#!/bin/bash

function build()
{
    #mvn package -DskipTests > /dev/null 2>&1
    mvn clean package -DskipTests
}

function get_pid()
{
    port=$1
    pid=$(lsof -i tcp:$port|grep 'LISTEN'|awk '{print $2}');
    if [ -n $pid ];then
        echo $pid
    else
        echo 0
    fi
}

function start()
{    
    proj=$1
    port=$2
    profile=$3
    echo "run app $proj"
    cd $cur
    
    options=""
    if [ ! -z $port ];then
        options="--server.port=${port}"
    fi
    if [ ! -z $profile ];then
        options="${options} -Dspring.profiles.active=${profile}"
    fi
    echo "options: ${options}"
    #nohup java -Xmx200m -jar $proj/target/$proj-0.0.1-SNAPSHOT.jar $options > /dev/null 2>&1 &
    java -Xmx200m -jar $proj/target/$proj-0.0.1-SNAPSHOT.jar $options
}

function stop() 
{
    proj=$1
    port=$2
    pid=$(get_pid $port)
    pid=${pid:-0}
    if [ $pid -gt 0 ];then
        echo "stop app $proj at port $port for pid $pid"
        kill $pid
    else
        echo "app $proj is not running"
    fi
}

cur=$(pwd)
name=`basename $0 .sh`
app=$2
port=$3
profile=$4

sysOS=`uname -s`
if [ $sysOS != "Darwin" ];then 
    echo "${name} only support macos system!!!"
    exit 0
fi

case $1 in
    start)
        build
        start $app $port $profile
    ;;
    stop)
        stop $app $port
    ;;
    restart)
        stop $app $port
        start $app $port $profile
    ;;    
    *)
        echo "Usage: $name [start|stop|restart] {app} [port] [profile]"
    ;;
esac
exit 0

